---
inst_generation_params:
  SMALL_1:
    - type: drill
      num: 4
      time_windows: 2
      demand_mu: 25
      demand_sigma: 7
      frequencies:
        values: [1, 2]
        probs: [0.4, 0.6]
      name_prefix: 'd'
      default_time_window: 7, 19
      departure_spread: 1
      deck_service_speed: 10
    - type: prod
      num: 6
      time_windows: 3
      demand_mu: 20
      demand_sigma: 5
      frequencies:
        values: [1, 2, 3]
        probs: [0.4, 0.4, 0.2]
      name_prefix: 'p'
      default_time_window: 7, 19
      departure_spread: 1
      deck_service_speed: 10
  SMALL_2:
    - type: drill
      num: 6
      time_windows: 3
      demand_mu: 25
      demand_sigma: 7
      frequencies:
        values: [ 1, 2 ]
        probs: [ 0.4, 0.6 ]
      name_prefix: 'd'
      default_time_window: 7, 19
      departure_spread: 1
      deck_service_speed: 10
    - type: prod
      num: 8
      time_windows: 5
      demand_mu: 20
      demand_sigma: 5
      frequencies:
        values: [ 1, 2, 3 ]
        probs: [ 0.4, 0.3, 0.3 ]
      name_prefix: 'p'
      default_time_window: 7, 19
      departure_spread: 1
      deck_service_speed: 10

fleet_generation_params:
  SMALL_1:
    - type: vtype1
      name_prefix: 'v'
      num: 8
      speed: 12
      fcs: 0.43
      fcw: 0.26
      deck_capacity: 100
      bulk_capacity: 1000
      cost: 0
  SMALL_2:
    - type: vtype1
      name_prefix: 'v'
      num: 8
      speed: 12
      fcs: 0.43
      fcw: 0.26
      deck_capacity: 100
      bulk_capacity: 1000
      cost: 0

base_generation_params:
  FMO:
    service_time: 8
    time_window: 8, 16

inst_coords:
  [[60.78, 3.55], [61.04, 3.56], [61.17, 2.18], [61.2, 2.2],
   [61.2,  2.27], [60.8558,  2.6503], [61.07, 2.5], [60.48, 2.82], [60.6, 2.77],
   [60.48, 2.82], [60.7, 2.93], [60.38, 2.79], [61.055, 2.03], [60.53, 2.68],
   [60.7, 3.51], [60.93, 3.66], [60.7, 2.93], [61.25, 1.85],
   [61.2, 1.82], [61.29, 1.9], [60.77, 3.5], [60.89, 3.6], [60.64, 3.72],
   [61.04, 2.34], [60.78, 2.89], [61.04, 2.34], [60.77, 2.89], [61.37, 2.45],
   [60.5, 4.8]]

base_coords:
  FMO: [60.7945, 5.063]
  OP_FMO : [60.7942, 4.695]