---
data_path:
  vessels: ['data', 'vessels']
  installations: ['data', 'installations']
  base: ['data', 'base']
  solution: ['data', 'solutions']

sample_path:
  vessels: ['sample', 'vessels']
  installations: ['sample', 'installations']
  base: ['sample', 'base']
  solution: ['sample', 'solutions']

dataset_name:
  installations:
    prefix: 'i_'
    suffix: '.pkl'
  vessels:
    prefix: 'v_'
    suffix: '.pkl'
  base:
    prefix: 'b_'
    suffix: '.pkl'
#    FMO: 'FMO.pkl'
  solution:
    prefix: 'sol_'
    suffix: '.pkl'
#    sol1_small_1: 'sol1_small_1.pkl'
#    sol2_small_1: 'sol2_small_1.pkl'
#    sol1_small_2: 'sol1_small_2.pkl'
#    sol2_small_2: 'sol2_small_2.pkl'
